---
version: '3'
services:
  db:
    image: az82/docker-derby
    container_name: apache-derby-tmp
    restart: always
    ports:
      - 1527:1527

  app:
    image: Application.jar
    container_name: application
    environment:
      JAVA_OPTIONS: '-Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1089 -Xms64m -Xmx512m '
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db