 create table url (
    id bigint generated by default as identity,
    original_url varchar(255),
    short_url varchar(50),
    created_time timestamp,
    url_value varchar(45),
    primary key (id)
)
